### ISSUE TITLE
Throw from frodo-lib

### ISSUE THREAD

**Issue by aphillipohl** [rockcarver/frodo-lib#231] opened 2023-03-29 10:38 UTC
## Frodo Library version

*Latest version - Github main*

We are tracking this issue here for frodo-lib as we agreed that frodo-lib would always throw on errors.

Getting you guys a Draft PR to make certain we are heading in the correct direction.

## Describe the issue
Currently we want the CLI to return a non-zero error code when we have API or other errors, to be able to do this it seems sensible that the library throw errors.

A first pass at this might be to rethrow any errors we find or if many possible errors can occur we might need to wrap the errors at some point and not print out messages at all but add them to sensibly named error classes.

**Comment by aphillipohl** [comment] 2023-03-29 10:40
@vscheuber hey Volker it would be good to be able to edit labels, not sure what the rules github needs for that are?

**Comment by vscheuber** [comment] 2023-03-29 13:38
@aphillipohl let me know which labels are missing and I can create them. I am not sure what the general public access is, but I can freely select from a list of labels and create new ones. Can you see the list of existing labels? I flagged this one as an `enhancement`.

**Comment by vscheuber** [comment] 2023-04-18 03:59
@aphillipohl I have merged #234, which contains some of the ideas you had in #233. I have not marked this issue closed, yet, just because the core of this issue was not the main focus of #234 .

If you and your team get a chance, please check it out and maybe even rebase #233 and see where that gets you.

Just as an FYI: I also noticed that on the CLI side there was a regression introduced in rockcarver/frodo-cli#186 which caused frodo to return exit code 0 no matter what any of the command tried to return explicitly. I addressed that in rockcarver/frodo-cli#223.

Both the updated frodo-lib 0.18.9-3 and frodo-cli 0.23.1-3 are pre-releases, so the release notes are not complete and an npm install will not install them unless you explicitly request it with `npm i @rockcarver/frodo-cli@next`

**Comment by vscheuber** [comment] 2023-11-03 17:17
We have adapted this concept across all of frodo-lib where possible with very few areas still outstanding. Closing this as complete.

**Closed by vscheuber** 2023-11-03 17:17 UTC
Labels: enhancement
